name: I'm David D Lawson
title: David D Lawson
t:
  en:
    home: "I'm David D Lawson"
  it:
    home: "Sono David D Lawson"
  fr:
    home: "Je suis David D Lawson"

### WEBSITE URL SETTINGS
## Development 
url: ""
baseurl: ""
## Production
# url: http://ddlawson.com
# baseurl: http://ddlawson.com

### OTHER SETTINGS
markdown: kramdown