### Site Settings
name: I'm David D Lawson
title: David D Lawson
destination: ./docs

### Multilingual Settings
t:
  en:
    home: "I'm David D Lawson"
  it:
    home: "Sono David D Lawson"
  fr:
    home: "Je suis David D Lawson"

### Website URL Settings
# Development 
url: ""
baseurl: ""
# Production
# url: http://ddlawson.com
# baseurl: http://ddlawson.com

### Exclude Settings
exclude: [
# folders
'node_modules',
'original',
'licenses',
'assets',
# files
'Gemfile',
'Gemfile.lock',
'Gruntfile.js',
'LICENSE.md',
'README.md',
'cv.sublime-project',
'cv.sublime-workspace',
'package.json',
'package-lock.json'
]

### Stop Jekyll from overwriting Grunt-minified HTML files
exclude: ['index.html', 'it/index.html', fr/index.html]
keep_files: ['index.html', 'it/index.html', fr/index.html]

### Other Settings
layouts_dir: _layouts_min
strict_front_matter: true
markdown: kramdown