### Site Settings
name: I'm David D Lawson
title: David D Lawson

### Multilingual Settings
t:
  en:
    home: "I'm David D Lawson"
  it:
    home: "Sono David D Lawson"
  fr:
    home: "Je suis David D Lawson"

### Website URL Settings
# Development 
url: ""
baseurl: ""
# Production
# url: http://ddlawson.com
# baseurl: http://ddlawson.com

### Exclude Settings
exclude: [
# folders
'node_modules',
'original',
'licenses',
'assets',
# files
'Gemfile',
'Gemfile.lock',
'Gruntfile.js',
'LICENSE.md',
'README.md',
'cv.sublime-project',
'cv.sublime-workspace',
'package.json',
'package-lock.json'
]

### Other Settings
markdown: kramdown