name: I'm David D Lawson
title: David D Lawson

### WEBSITE URL SETTINGS
## Development 
url: ""
baseurl: ""
## Production
# url: http://ddlawson.com
# baseurl: http://ddlawson.com

### OTHER SETTINGS
markdown: kramdown